### ISSUE TITLE
scala.MatchError , Any idea?>

### ISSUE THREAD

**Issue by Bennyelg** [idio/sbt-assembly-log4j2#7]
**scala.MatchError: com/fasterxml/jackson/databind/node/ValueNode.class (of class java.lang.String)**
	at $8cb81fc39ba4bfc44da2$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/Users/benny/Work/Projects/load-index-calculator/build.sbt:35)
	at $8cb81fc39ba4bfc44da2$$anonfun$$sbtdef$1$$anonfun$apply$1.apply(/Users/benny/Work/Projects/load-index-calculator/build.sbt:35)
	at sbtassembly.Assembly$$anonfun$9.apply(Assembly.scala:113)
	at sbtassembly.Assembly$$anonfun$9.apply(Assembly.scala:112)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:112)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:240)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:237)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
**[error] (*:assembly) scala.MatchError: com/fasterxml/jackson/databind/node/ValueNode.class (of class java.lang.String)**
[error] Total time: 38 s, completed Apr 3, 2017 10:07:24 AM

**Comment by keynmol** [comment]
Hi.

Without seeing your code in `build.sbt` it's hard to say what's the issue here, but I would guess that you didn't provide a default assembly strategy matcher, as [specified in the documentation for sbt-assembly](https://github.com/sbt/sbt-assembly#merge-strategy)

I.e. the general way of using this plugin is as such:

```scala
assemblyMergeStrategy in assembly := {
  // your other merging rules go here
  // ...
  // merge strategy provided by this plugin
  case PathList(ps @ _*) if ps.last == "Log4j2Plugins.dat" => Log4j2MergeStrategy.plugincache
  // sbt-assembly's default merge strategy applied to all the files that didn't match previous rules
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}

```

**Comment by Bennyelg** [comment]
Hey, Here it is.

name := "load_index"

version := "1.0"

scalaVersion := "2.11.8"

resolvers += "Spark Package Main Repo" at "https://dl.bintray.com/spark-packages/maven"
libraryDependencies += "io.logz.log4j2" % "logzio-log4j2-appender" % "1.0.3"
libraryDependencies += "org.apache.logging.log4j" % "log4j-core" % "2.8.1"
libraryDependencies += "org.apache.logging.log4j" % "log4j-api" % "2.8.1"
libraryDependencies += "org.apache.logging.log4j" %% "log4j-api-scala" % "2.8.1"

assemblyMergeStrategy in assembly := {
  case x if x.contains("/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat") => MergeStrategy.first
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}

**Comment by keynmol** [comment]
- Your code doesn't appear to use our plugin at all
- the build.sbt you provided is less than 35 lines (35th line is mentioned in the stack trace)

So far I cannot confirm that your error is related to our plugin at all.

**Comment by keynmol** [comment]
After changing your `build.sbt` as such:

```scala
name := "load_index"

version := "1.0"

scalaVersion := "2.11.8"

import sbtassembly.Log4j2MergeStrategy

resolvers += "Spark Package Main Repo" at "https://dl.bintray.com/spark-packages/maven"
libraryDependencies += "io.logz.log4j2" % "logzio-log4j2-appender" % "1.0.3"
libraryDependencies += "org.apache.logging.log4j" % "log4j-core" % "2.8.1"
libraryDependencies += "org.apache.logging.log4j" % "log4j-api" % "2.8.1"
libraryDependencies += "org.apache.logging.log4j" %% "log4j-api-scala" % "2.8.1"

assemblyMergeStrategy in assembly := {
// your other merging rules go here
// ...
// merge strategy provided by this plugin
case PathList(ps @ _*) if ps.last == "Log4j2Plugins.dat" => Log4j2MergeStrategy.plugincache
// sbt-assembly's default merge strategy applied to all the files that didn't match previous rules
case x =>
val oldStrategy = (assemblyMergeStrategy in assembly).value
oldStrategy(x)
}
```

and adding those to `project/plugins.sbt`

```scala
resolvers += Resolver.url(
  "idio",
  url("http://dl.bintray.com/idio/sbt-plugins")
)(Resolver.ivyStylePatterns)

addSbtPlugin("org.idio" % "sbt-assembly-log4j2" % "0.1.0")
```

Running `sbt assembly` finishes successfully:

```
...
[warn] Merging 'META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat' with strategy 'log4j2::plugincache'
[info] Strategy 'deduplicate' was applied to 974 files (Run the task at debug level to see details)
[warn] Strategy 'discard' was applied to 20 files
[warn] Strategy 'log4j2::plugincache' was applied to a file
[warn] Strategy 'rename' was applied to 2 files
[info] SHA-1: 22669a8544c1e770f5155467c19034e4fd3769c5
[info] Packaging /private/var/folders/_6/s7g00yqs4_x1m_d7z26_0jqw0000gn/T/tmp.hb8ww0vb/target/scala-2.11/load_index-assembly-1.0.jar ...
[info] Done packaging.
[success] Total time: 19 s, completed 03-Apr-2017 09:29:21
```

So far I'm not convinced that our plugin is related to the exception you're seeing.

**Comment by Bennyelg** [comment]
Thanks, I did a dummy mistake. everything works.

**Comment by keynmol** [comment]
No worries. Thanks for using our plugin!
